name: Build

on: 
  push:
    branches:
      - main

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp38-*"
          CIBW_ARCHS_MACOS: arm64 x86_64
          CIBW_BEFORE_BUILD: pip install -r requirements.txt

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  publish:
      name: Publish distribution 📦 to PyPI
      runs-on: ubuntu-latest
      needs: build_wheels
      steps:
        - uses: actions/download-artifact@v3
          with:
            name: wheels
            path: dist
        - uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.PYPI_API_TOKEN }}